import 'dotenv/config';

export const r2Config = {
  endpoint: process.env.R2_END_POINT,
  bucketName: process.env.R2_BUCKET_NAME,
  accessKeyId: process.env.R2_ACCESS_KEY_ID,
  secretAccessKey: process.env.R2_SECRET_ACCESS_KEY,
  publicPath: process.env.R2_PUBLIC_PATH,
  region: 'auto',
};

export const allowedImageTypes = [
  'image/jpeg',
  'image/jpg',
  'image/png',
  'image/gif',
  'image/webp',
  'image/svg+xml',
  'image/bmp',
  'image/tiff',
  'image/avif',
  'image/x-canon-cr2',
  'image/x-canon-cr3',
  'image/x-canon-crw',
  'image/x-nikon-nef',
  'image/x-nikon-nrw',
  'image/x-sony-arw',
  'image/x-sony-srf',
  'image/x-sony-sr2',
  'image/x-adobe-dng',
  'image/x-olympus-orf',
  'image/x-panasonic-rw2',
  'image/x-pentax-pef',
  'image/x-fuji-raf',
  'image/x-hasselblad-3fr',
  'image/x-kodak-dcr',
  'image/x-kodak-k25',
  'image/x-kodak-kdc',
  'image/x-minolta-mrw',
  'image/x-epson-erf',
  'image/x-sigma-x3f',
  'image/x-raw',
  'application/octet-stream',
];

export const allowedImageExtensions = [
  '.jpg',
  '.jpeg',
  '.png',
  '.gif',
  '.webp',
  '.svg',
  '.bmp',
  '.tiff',
  '.tif',
  '.avif',
  '.cr2',
  '.cr3',
  '.crw',
  '.nef',
  '.nrw',
  '.arw',
  '.srf',
  '.sr2',
  '.dng',
  '.orf',
  '.rw2',
  '.pef',
  '.ptx',
  '.raf',
  '.3fr',
  '.dcr',
  '.k25',
  '.kdc',
  '.mrw',
  '.raw',
  '.rwl',
  '.iiq',
  '.erf',
  '.mos',
  '.x3f',
];

export const maxFileSize = 100 * 1024 * 1024;
